### PR TITLE
Inflection-66 Fix --ignore-entries-with-grammemes in dictionary-parser and improve language variant handling

### LINKED ISSUE #66: Fix --ignore-entries-with-grammemes in dictionary-parser and improve language variant handling
There are some changes that are needed to fix --ignore-entries-with-grammemes and improve language variant handling.

### PR DESCRIPTION
**Pull request by grhoten**
Resolves #66

These changes reduce the failures for English, but it doesn't fully fix the issues yet. It's an improvement and a step in the right direction.

### CODE REVIEW

File: inflection/tools/dictionary-parser/src/main/java/org/unicode/wikidata/ParseWikidata.java [hunk 1]
```diff
@@ -489,6 +505,21 @@ private void analyzeLexeme(Lexeme lexeme) {
...
+                currentLemmaLanguage = currentLemmaLanguage.substring(0, qVariantIdx);
+                var variant = Grammar.getMappedGrammemes(additionalCategory);
+                if (variant == null) {
+                    if (parserOptions.debug) {
+                        System.err.println("Line " + lineNumber + ": " + additionalCategory + " is not a known grammeme for the language variant " + lexeme.id + "(" + lemma.value + ")");
+                    }
+                    continue;
+                }
+                lemma.grammemes.addAll(variant);
+            }
```
Comment (grhoten) [inline inflection/tools/dictionary-parser/src/main/java/org/unicode/wikidata/ParseWikidata.java:522]: This chunk helps with ignoring some of the variants. This might need to be extended further for the inflections.

File: inflection/tools/dictionary-parser/src/main/java/org/unicode/wikidata/ParseWikidata.java [hunk 2]
```diff
@@ -301,6 +287,34 @@ private static void printUsage() {
...
+                                clone.add(ignorable);
+                                entry.setValue(new HashSet<>(clone));
+                            }
+                            break;
+                        }
+                    }
+                }
+            }
+        }
+    }
```
Comment (grhoten) [inline inflection/tools/dictionary-parser/src/main/java/org/unicode/wikidata/ParseWikidata.java:317]: This fixes the ignorable properties and ignorable inflections, which tend to include a lot of irrelevant information.

File: inflection/tools/dictionary-parser/src/main/java/org/unicode/wikidata/Grammar.java [hunk 3]
```diff
@@ -554,11 +537,7 @@ public String toString() {
         }
     }
 
-    public static SortedSet<String> asSet(String... terms) {
-        return new TreeSet<>(Arrays.asList(terms));
-    }
-
-    static final Map<SortedSet<String>, Set<? extends Enum<?>>> TYPEMAP = new HashMap<>(1021);
+    static final Map<String, Set<? extends Enum<?>>> TYPEMAP = new HashMap<>(1021);
```
Comment (grhoten) [inline inflection/tools/dictionary-parser/src/main/java/org/unicode/wikidata/Grammar.java:540]: I changed the key type, since Wikidata doesn't include a key set. This is a simplification.

**Review by nciric — APPROVED** [review]
